const zhTeams={"Mexico":"墨西哥","South Africa":"南非","South Korea":"南韓","Czech Republic":"捷克","Canada":"加拿大","Bosnia & Herzegovina":"波士尼亞與赫塞哥維納","Qatar":"卡達","Switzerland":"瑞士","Brazil":"巴西","Morocco":"摩洛哥","Haiti":"海地","Scotland":"蘇格蘭","United States":"美國","Paraguay":"巴拉圭","Australia":"澳洲","Turkey":"土耳其","Germany":"德國","Ivory Coast":"象牙海岸","Ecuador":"厄瓜多","Curaçao":"古拉索","Netherlands":"荷蘭","Japan":"日本","Sweden":"瑞典","Tunisia":"突尼西亞","Belgium":"比利時","Egypt":"埃及","Iran":"伊朗","New Zealand":"紐西蘭","Spain":"西班牙","Cape Verde":"維德角","Saudi Arabia":"沙烏地阿拉伯","Uruguay":"烏拉圭","France":"法國","Senegal":"塞內加爾","Iraq":"伊拉克","Norway":"挪威","Argentina":"阿根廷","Algeria":"阿爾及利亞","Austria":"奧地利","Jordan":"約旦","Portugal":"葡萄牙","Colombia":"哥倫比亞","Uzbekistan":"烏茲別克","England":"英格蘭","Croatia":"克羅埃西亞","Ghana":"迦納","Panama":"巴拿馬"};
const flags={"Mexico":"🇲🇽","South Africa":"🇿🇦","South Korea":"🇰🇷","Czech Republic":"🇨🇿","Canada":"🇨🇦","Bosnia & Herzegovina":"🇧🇦","Qatar":"🇶🇦","Switzerland":"🇨🇭","Brazil":"🇧🇷","Morocco":"🇲🇦","Haiti":"🇭🇹","Scotland":"🏴󠁧󠁢󠁳󠁣󠁴󠁿","United States":"🇺🇸","Paraguay":"🇵🇾","Australia":"🇦🇺","Turkey":"🇹🇷","Germany":"🇩🇪","Ivory Coast":"🇨🇮","Ecuador":"🇪🇨","Curaçao":"🇨🇼","Netherlands":"🇳🇱","Japan":"🇯🇵","Sweden":"🇸🇪","Tunisia":"🇹🇳","Belgium":"🇧🇪","Egypt":"🇪🇬","Iran":"🇮🇷","New Zealand":"🇳🇿","Spain":"🇪🇸","Cape Verde":"🇨🇻","Saudi Arabia":"🇸🇦","Uruguay":"🇺🇾","France":"🇫🇷","Senegal":"🇸🇳","Iraq":"🇮🇶","Norway":"🇳🇴","Argentina":"🇦🇷","Algeria":"🇩🇿","Austria":"🇦🇹","Jordan":"🇯🇴","Portugal":"🇵🇹","Colombia":"🇨🇴","Uzbekistan":"🇺🇿","England":"🏴󠁧󠁢󠁥󠁮󠁧󠁿","Croatia":"🇭🇷","Ghana":"🇬🇭","Panama":"🇵🇦"};
zhTeams.USA='美國';flags.USA='🇺🇸';
const t=n=>zhTeams[n]||n; const fmt=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false});
let matches=[];let groupStats=new Map();let scorerData=[];
async function boot(){try{const data=await fetch('data/site-data.json?'+Date.now()).then(r=>r.json());matches=data.matches||[];scorerData=data.scorers||[];groupStats=new Map((data.groups||[]).flatMap(g=>g.teams.map(x=>[x.team,x])));renderDates();renderGroups(data.groups||[]);renderBracket();renderScorers(scorerData);renderNews(data.news||[]);renderVideos(data.videos||[]);renderOdds(data.odds||[]);document.querySelector('#update-label').textContent=`資料更新：${new Date(data.updatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}`;}catch(e){document.querySelector('#match-list').innerHTML='<p class="loading">資料暫時無法載入，請稍後重試。</p>'}}
function localDate(m){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date(m.kickoff));}
function renderDates(){const base=new Date(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date())+'T12:00:00+08:00');const labels=['昨天','今天','明天','後天','大後天','四天後','五天後'];const dates=[-1,0,1,2,3,4,5].map((offset,i)=>{const x=new Date(base);x.setDate(x.getDate()+offset);return{date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(x),label:labels[i],x}});let selected=dates[1].date;const strip=document.querySelector('#date-strip');strip.innerHTML=dates.map(({date,label,x})=>`<button class="date-btn ${date===selected?'active':''}" data-date="${date}"><span class="relative-day">${label}</span><strong>${x.getDate()}</strong><span>${x.getMonth()+1}月・${x.toLocaleDateString('zh-TW',{weekday:'short'})}</span></button>`).join('');strip.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.date;strip.querySelector('.active')?.classList.remove('active');b.classList.add('active');renderMatches(selected)});renderMatches(selected);}
function teamForm(team){const s=groupStats.get(team);return s?`<small class="team-form"><b>${s.points} 分</b>｜${s.won} 勝 ${s.drawn} 和 ${s.lost} 負</small>`:'<small class="team-form">小組戰績待定</small>'}
function matchScore(m){if(!Array.isArray(m.score))return '<span class="vs">VS</span>';const shootout=Array.isArray(m.penalties)?`<small>PK ${m.penalties[0]}－${m.penalties[1]}</small>`:'';const aet=Array.isArray(m.extraTime)&&!shootout?'<small>延長賽</small>':'';return `${m.score[0]} <span>－</span> ${m.score[1]}${shootout||aet}`}
function renderMatches(date){const list=matches.filter(m=>localDate(m)===date).sort((a,b)=>a.kickoff.localeCompare(b.kickoff));document.querySelector('#match-list').innerHTML=list.length?list.map(m=>{const d=new Date(m.kickoff);const time=d.toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false});const played=Array.isArray(m.score);return `<article class="match-card"><div class="match-time">${time}</div><div class="team"><button class="team-link" data-team="${m.team1}"><i class="match-flag">${flags[m.team1]||'🏳️'}</i>${t(m.team1)}</button>${teamForm(m.team1)}</div><div class="score">${matchScore(m)}</div><div class="team away"><button class="team-link" data-team="${m.team2}"><i class="match-flag">${flags[m.team2]||'🏳️'}</i>${t(m.team2)}</button>${teamForm(m.team2)}</div><div class="meta"><span class="badge">${m.group||m.round}</span><br>${m.ground||'場地待定'} · ${played?'完場':'未開賽'}</div></article>`}).join(''):'<div class="no-matches"><strong>本日沒有賽事</strong><span>所有日期與時間均為台灣時間（UTC+8）</span></div>'}
function renderGroups(groups){
  if(!groups.length){document.querySelector('#group-board').innerHTML='<p class="loading">小組資料載入中…</p>';return}
  let active=0;
  const isComplete=g=>g.teams.reduce((n,x)=>n+x.played,0)>=12;
  const allComplete=groups.every(isComplete);
  const bestThird=new Set(allComplete?groups.map(g=>g.teams[2]).sort((a,b)=>b.points-a.points||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf||a.team.localeCompare(b.team)).slice(0,8).map(x=>x.team):[]);
  const stateFor=(team,rank,complete)=>{if(rank<2)return{label:complete?'已晉級':'晉級區',cls:complete?'qualified':''};if(rank===2){if(!allComplete)return{label:'競逐中',cls:''};return bestThird.has(team)?{label:'已晉級',cls:'qualified'}:{label:'已淘汰',cls:'eliminated'}}return{label:complete?'已淘汰':'待定',cls:complete?'eliminated':''}};
  const tabs=document.querySelector('#group-tabs');
  tabs.innerHTML=groups.map((g,i)=>`<button class="group-tab ${i===0?'active':''}" data-i="${i}">${g.name.replace('Group ','')} 組</button>`).join('');
  const draw=()=>{const g=groups[active],completed=isComplete(g),second=g.teams[1],third=g.teams[2],gd=x=>x.gf-x.ga,fmt=n=>n>0?`+${n}`:String(n),note=completed&&second.points===third.points?`<p class="group-explain">${t(second.team)}與${t(third.team)}同為 ${second.points} 分；${gd(second)!==gd(third)?`${t(second.team)}得失球差 ${fmt(gd(second))}，優於${t(third.team)}的 ${fmt(gd(third))}`:`得失球差相同，${t(second.team)}以進球數 ${second.gf} 比 ${third.gf} 領先`}，因此排名第二。<a href="https://www.fifa.com/en/articles/groups-how-teams-qualify-tie-breakers" target="_blank" rel="noopener">同分規則 ↗</a></p>`:'';document.querySelector('#group-board').innerHTML=`<div class="group-table"><div class="group-title">${g.name.replace('Group ','')} 組排名</div><div class="group-row header"><span>#</span><span>國家</span><span>賽</span><span>勝</span><span>和</span><span>負</span><span>分</span><span>狀態</span></div>${g.teams.map((x,i)=>{const s=stateFor(x.team,i,completed);return `<div class="group-row ${i<2?'qualify':i===2?'third-place':''}"><span class="rank">${i+1}</span><button class="club team-link" data-team="${x.team}"><i class="flag">${flags[x.team]||'🏳️'}</i>${t(x.team)}</button><span>${x.played}</span><span>${x.won}</span><span>${x.drawn}</span><span>${x.lost}</span><span class="pts">${x.points}</span><span class="state ${s.cls}">${s.label}</span></div>`}).join('')}${note}</div>`};
  tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=+b.dataset.i;tabs.querySelector('.active')?.classList.remove('active');b.classList.add('active');draw()});draw()
}
function slotName(slot){const raw=String(slot||'待定'),ref=raw.match(/^([WL])(\d+)$/);if(ref){const source=matches.find(x=>x.number===+ref[2]);if(source&&Array.isArray(source.score)){const winner=source.score[0]>source.score[1]?source.team1:source.team2;const loser=source.score[0]>source.score[1]?source.team2:source.team1;return ref[1]==='W'?winner:loser}return `第${ref[2]}場${ref[1]==='W'?'勝者':'敗者'}`}const multi=raw.match(/^3([A-L](?:\/[A-L])+)/);if(multi)return `最佳第三 ${multi[1]}`;const group=raw.match(/^([123])([A-L])$/);if(group)return `${group[2]}組第${group[1]}`;return raw}
function bracketTeam(slot,score,winner,penalty){const name=slotName(slot),known=flags[name];return `<div class="bracket-team ${winner?'winner':''} ${known?'':'placeholder'}">${known?`<button class="team-link" data-team="${name}"><i>${known}</i>${t(name)}</button>`:`<span><i>🏳️</i>${t(name)}</span>`}<b>${score??'—'}${penalty!==undefined?` <small>(${penalty})</small>`:''}</b></div>`}
function renderBracket(){const stages=[['Round of 32','32 強'],['Round of 16','16 強'],['Quarter-final','8 強'],['Semi-final','準決賽'],['Final','決賽']];document.querySelector('#bracket-board').innerHTML=stages.map(([key,title])=>{const games=matches.filter(m=>m.round===key);return `<section class="bracket-stage"><h3>${title}<small>${games.length} 場</small></h3><div class="stage-games">${games.map(m=>{const played=Array.isArray(m.score),shootout=Array.isArray(m.penalties),deciding=shootout?m.penalties:m.score,one=played&&deciding?.[0]>deciding?.[1],two=played&&deciding?.[1]>deciding?.[0],note=shootout?`・PK ${m.penalties[0]}－${m.penalties[1]}`:Array.isArray(m.extraTime)?'・延長賽':'';const dt=new Date(m.kickoff).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});return `<article class="bracket-match"><div class="match-no">第 ${m.number} 場・${dt}${note}</div>${bracketTeam(m.team1,m.score?.[0],one,m.penalties?.[0])}${bracketTeam(m.team2,m.score?.[1],two,m.penalties?.[1])}</article>`}).join('')}</div></section>`}).join('')}
function renderScorers(items){document.querySelector('#scorer-list').innerHTML=items.length?items.slice(0,12).map((x,i)=>`<div class="scorer-row"><span class="scorer-rank">${String(i+1).padStart(2,'0')}</span><span class="scorer-name"><button class="player-link" data-player="${i}" title="查看 ${x.name} 球員資料">${x.name}</button><small class="scorer-team">${flags[x.team]||'🏳️'} ${t(x.team)}</small></span><span class="goal-count">${x.goals}<small>GOALS</small></span></div>`).join(''):'<div class="empty">尚無進球資料。</div>'}
function renderNews(items){document.querySelector('#news-grid').innerHTML=items.length?items.slice(0,6).map(n=>`<a class="news-card" href="${n.link}" target="_blank" rel="noopener"><div><span class="news-source">${n.source||'中文新聞'}</span><h3>${n.title}</h3></div><p>${new Date(n.pubDate).toLocaleDateString('zh-TW')}　閱讀全文 ↗</p></a>`).join(''):'<div class="empty">目前無法取得中文新聞，請點右上方「更多新聞」。</div>'}
function renderVideos(items){document.querySelector('#video-grid').innerHTML=items.length?items.map(v=>`<article class="video-embed"><div class="iframe-wrap"><iframe src="https://www.youtube.com/embed/${v.id}?rel=0&playsinline=1" title="${v.title.replace(/"/g,'&quot;')}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><p>${v.label}</p><h3>${v.title}</h3><a href="${v.url}" target="_blank" rel="noopener">無法播放？前往 YouTube ↗</a></article>`).join(''):'<div class="no-matches"><strong>影片暫時無法載入</strong><span>請稍後重新整理。</span></div>'}
function renderOdds(items){document.querySelector('#odds-grid').innerHTML=items.length?items.slice(0,9).map(o=>`<article class="odds-card"><div class="odds-teams">${t(o.home)} vs ${t(o.away)}</div><div class="markets"><div class="market">${t(o.home)}<strong>${o.homePrice}</strong></div><div class="market">和局<strong>${o.drawPrice}</strong></div><div class="market">${t(o.away)}<strong>${o.awayPrice}</strong></div></div></article>`).join(''):'<div class="empty"><strong>賠率資料尚未接通</strong><br>在 GitHub Repository Secrets 加入 <code>ODDS_API_KEY</code> 後，排程會自動抓取 1X2 賠率。此區不會顯示虛構數字。</div>'}
function openTeamHistory(team){const dialog=document.querySelector('#team-dialog'),content=document.querySelector('#team-dialog-content'),games=matches.filter(m=>m.team1===team||m.team2===team).sort((a,b)=>a.kickoff.localeCompare(b.kickoff));content.innerHTML=`<header class="team-dialog-head"><h3>${flags[team]||'🏳️'} ${t(team)}</h3><p>本屆世界盃完整賽程・台灣時間</p></header><div class="history-list">${games.map(m=>{const home=m.team1===team,opponent=home?m.team2:m.team1,date=new Date(m.kickoff).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}),played=Array.isArray(m.score),score=played?`${home?m.score[0]:m.score[1]}－${home?m.score[1]:m.score[0]}`:'未開賽';return `<div class="history-row"><span class="history-date">${date}</span><span class="history-opponent">vs ${flags[opponent]||'🏳️'} ${t(opponent)}</span><span class="history-score ${played?'':'upcoming'}">${score}</span></div>`}).join('')}</div>`;dialog.showModal()}
function openPlayerProfile(index){const player=scorerData[index];if(!player)return;const dialog=document.querySelector('#player-dialog'),content=document.querySelector('#player-dialog-content'),photo=player.profile?.photo;content.innerHTML=`<header class="player-profile">${photo?`<img src="${photo}" alt="${player.name}">`:`<div class="player-fallback">${player.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}</div>`}<div><p>${flags[player.team]||'🏳️'} ${t(player.team)}</p><h3>${player.name}</h3><span>${player.profile?.bio||`${t(player.team)}國家隊球員`}</span></div></header><div class="player-total"><b>${player.goals}</b><span>本屆世界盃進球</span></div><div class="history-list"><h4>進球場次</h4>${(player.matches||[]).map(m=>{const score=Array.isArray(m.score)?`${m.score[0]}－${m.score[1]}`:'賽果待定',date=new Date(m.kickoff).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});return `<div class="history-row player-goal-row"><span class="history-date">${date}</span><span class="history-opponent">vs ${flags[m.opponent]||'🏳️'} ${t(m.opponent)}<small>第 ${m.number} 場・${score}</small></span><span class="history-score">${m.goals} 球</span></div>`}).join('')}</div>`;dialog.showModal()}
document.addEventListener('click',e=>{const team=e.target.closest('.team-link')?.dataset.team;if(team)openTeamHistory(team);const player=e.target.closest('.player-link')?.dataset.player;if(player!==undefined)openPlayerProfile(+player);const close=e.target.closest('.dialog-close');if(close)close.closest('dialog').close();if(e.target.matches('dialog[open]'))e.target.close()});
boot();
