const sportNames=['全部','環法','F1','世界盃','道奇','中職','NFL','UFC','NBA季後賽','MLB季後賽'];let all=[],days=7,active='全部';const fmtDate=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',month:'numeric',day:'numeric',weekday:'short'}),fmtTime=new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false});
const zhNames={
  'Los Angeles Dodgers':'洛杉磯道奇','Arizona Diamondbacks':'亞利桑那響尾蛇','Atlanta Braves':'亞特蘭大勇士','Baltimore Orioles':'巴爾的摩金鶯','Boston Red Sox':'波士頓紅襪','Chicago Cubs':'芝加哥小熊','Chicago White Sox':'芝加哥白襪','Cincinnati Reds':'辛辛那提紅人','Cleveland Guardians':'克里夫蘭守護者','Colorado Rockies':'科羅拉多洛磯','Detroit Tigers':'底特律老虎','Houston Astros':'休士頓太空人','Kansas City Royals':'堪薩斯市皇家','Los Angeles Angels':'洛杉磯天使','Miami Marlins':'邁阿密馬林魚','Milwaukee Brewers':'密爾瓦基釀酒人','Minnesota Twins':'明尼蘇達雙城','New York Mets':'紐約大都會','New York Yankees':'紐約洋基','Athletics':'運動家','Philadelphia Phillies':'費城費城人','Pittsburgh Pirates':'匹茲堡海盜','San Diego Padres':'聖地牙哥教士','San Francisco Giants':'舊金山巨人','Seattle Mariners':'西雅圖水手','St. Louis Cardinals':'聖路易紅雀','Tampa Bay Rays':'坦帕灣光芒','Texas Rangers':'德州遊騎兵','Toronto Blue Jays':'多倫多藍鳥','Washington Nationals':'華盛頓國民',
  'Atlanta Hawks':'亞特蘭大老鷹','Boston Celtics':'波士頓塞爾提克','Brooklyn Nets':'布魯克林籃網','Charlotte Hornets':'夏洛特黃蜂','Chicago Bulls':'芝加哥公牛','Cleveland Cavaliers':'克里夫蘭騎士','Dallas Mavericks':'達拉斯獨行俠','Denver Nuggets':'丹佛金塊','Detroit Pistons':'底特律活塞','Golden State Warriors':'金州勇士','Houston Rockets':'休士頓火箭','Indiana Pacers':'印第安納溜馬','LA Clippers':'洛杉磯快艇','Los Angeles Clippers':'洛杉磯快艇','Los Angeles Lakers':'洛杉磯湖人','Memphis Grizzlies':'曼菲斯灰熊','Miami Heat':'邁阿密熱火','Milwaukee Bucks':'密爾瓦基公鹿','Minnesota Timberwolves':'明尼蘇達灰狼','New Orleans Pelicans':'紐奧良鵜鶘','New York Knicks':'紐約尼克','Oklahoma City Thunder':'奧克拉荷馬雷霆','Orlando Magic':'奧蘭多魔術','Philadelphia 76ers':'費城 76 人','Phoenix Suns':'鳳凰城太陽','Portland Trail Blazers':'波特蘭拓荒者','Sacramento Kings':'沙加緬度國王','San Antonio Spurs':'聖安東尼奧馬刺','Toronto Raptors':'多倫多暴龍','Utah Jazz':'猶他爵士','Washington Wizards':'華盛頓巫師',
  'Arizona Cardinals':'亞利桑那紅雀','Atlanta Falcons':'亞特蘭大獵鷹','Baltimore Ravens':'巴爾的摩烏鴉','Buffalo Bills':'水牛城比爾','Carolina Panthers':'卡羅萊納黑豹','Chicago Bears':'芝加哥熊','Cincinnati Bengals':'辛辛那提孟加拉虎','Cleveland Browns':'克里夫蘭布朗','Dallas Cowboys':'達拉斯牛仔','Denver Broncos':'丹佛野馬','Detroit Lions':'底特律雄獅','Green Bay Packers':'綠灣包裝工','Houston Texans':'休士頓德州人','Indianapolis Colts':'印第安納波利斯小馬','Jacksonville Jaguars':'傑克森維爾美洲虎','Kansas City Chiefs':'堪薩斯市酋長','Las Vegas Raiders':'拉斯維加斯突襲者','Los Angeles Chargers':'洛杉磯電光','Los Angeles Rams':'洛杉磯公羊','Miami Dolphins':'邁阿密海豚','Minnesota Vikings':'明尼蘇達維京人','New England Patriots':'新英格蘭愛國者','New Orleans Saints':'紐奧良聖徒','New York Giants':'紐約巨人','New York Jets':'紐約噴射機','Philadelphia Eagles':'費城老鷹','Pittsburgh Steelers':'匹茲堡鋼人','San Francisco 49ers':'舊金山 49 人','Seattle Seahawks':'西雅圖海鷹','Tampa Bay Buccaneers':'坦帕灣海盜','Tennessee Titans':'田納西泰坦','Washington Commanders':'華盛頓司令'
  ,'Algeria':'阿爾及利亞','Argentina':'阿根廷','Australia':'澳洲','Austria':'奧地利','Belgium':'比利時','Bosnia & Herzegovina':'波士尼亞與赫塞哥維納','Brazil':'巴西','Canada':'加拿大','Cape Verde':'維德角','Colombia':'哥倫比亞','Croatia':'克羅埃西亞','Curaçao':'庫拉索','Czech Republic':'捷克','DR Congo':'剛果民主共和國','Ecuador':'厄瓜多','Egypt':'埃及','England':'英格蘭','France':'法國','Germany':'德國','Ghana':'迦納','Haiti':'海地','Iran':'伊朗','Iraq':'伊拉克','Ivory Coast':'象牙海岸','Japan':'日本','Jordan':'約旦','Mexico':'墨西哥','Morocco':'摩洛哥','Netherlands':'荷蘭','New Zealand':'紐西蘭','Norway':'挪威','Panama':'巴拿馬','Paraguay':'巴拉圭','Portugal':'葡萄牙','Qatar':'卡達','Saudi Arabia':'沙烏地阿拉伯','Scotland':'蘇格蘭','Senegal':'塞內加爾','South Africa':'南非','South Korea':'南韓','Spain':'西班牙','Sweden':'瑞典','Switzerland':'瑞士','Tunisia':'突尼西亞','Turkey':'土耳其','USA':'美國','Uruguay':'烏拉圭','Uzbekistan':'烏茲別克'
};
const zhMeta={'regular-season':'例行賽','post-season':'季後賽','pre-season':'熱身賽','Round of 16':'16 強','Quarter-final':'半準決賽','Semi-final':'準決賽','Final':'決賽','Third-place match':'季軍戰'};
function zhText(text){return typeof text==='string'?Object.entries(zhNames).reduce((s,[en,zh])=>s.replaceAll(en,zh),zhMeta[text]||text):text}
function renderFilters(){const el=document.querySelector('#sport-filters');el.innerHTML=sportNames.map(x=>`<button class="${x===active?'active':''}" data-sport="${x}">${x}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.sport;renderFilters();render()})}
function dayKey(iso){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date(iso))}
function render(){const now=new Date(),end=new Date(now.getTime()+days*864e5),items=all.filter(x=>(active==='全部'||x.sport===active)&&new Date(x.start)>=new Date(now.getTime()-12*3600e3)&&new Date(x.start)<=end);const groups=Object.groupBy?Object.groupBy(items,x=>dayKey(x.start)):items.reduce((a,x)=>((a[dayKey(x.start)]||=[]).push(x),a),{});document.querySelector('#calendar').innerHTML=Object.keys(groups).length?Object.entries(groups).sort().map(([date,events])=>`<article class="day"><div class="day-date"><strong>${date.slice(5).replace('-','/')}</strong><span>${fmtDate.format(new Date(events[0].start))}</span></div><div class="events">${events.sort((a,b)=>a.start.localeCompare(b.start)).map(e=>`<div class="event" data-sport="${e.sport}"><div class="time">${e.timeTbd?'待定':fmtTime.format(new Date(e.start))}</div><div class="sport">${e.sport}</div><h3>${zhText(e.title)}<small>${zhText(e.subtitle)||''}</small>${e.distance||e.climb?`<span class="route-stats">${e.distance?`<i>距離 ${e.distance}</i>`:''}${e.climb?`<i>類型 ${e.climb}</i>`:''}${e.sport==='環法'?`<i>累積爬升 ${e.elevation?Number(e.elevation).toLocaleString()+' m':'未公布'}</i>`:''}</span>`:''}</h3><div class="channel">${e.mapUrl?`<a class="map-link" href="${e.mapUrl}" target="_blank" rel="noopener">地圖／爬升圖 ↗</a>`:''}${e.channelStatus||'MOD'} <b>${e.channel||'待定'}</b></div></div>`).join('')}</div></article>`).join(''):'<p class="loading">此範圍目前沒有已公布的賽事。</p>'}
async function boot(){const d=await fetch('data.json?'+Date.now()).then(r=>r.json());all=d.events||[];document.querySelector('#updated').textContent=`更新 ${new Date(d.updatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}`;document.querySelector('#pending-grid').innerHTML=(d.pending||[]).map(x=>`<div class="pending"><strong>${x.sport}</strong><span>${x.note}</span></div>`).join('');renderFilters();render();document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{days=+b.dataset.days;document.querySelector('[data-days].active')?.classList.remove('active');b.classList.add('active');render()})}boot();
